version: '3.8'

services:
  backend:
    build: ./herramientas-node-api
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=tienda
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_SYNC_ALTER=false
      - JWT_SECRET=cambiar-por-un-secreto-seguro
      - NODE_ENV=production
    depends_on:
      - db
    restart: unless-stopped
  
    labels:
      - "coolify.managed=true"
      - "coolify.port=3000"

  frontend:
    build: ./frontend-app
    environment:
      - VITE_API_URL=http://100.79.1.68:3000/api
    restart: unless-stopped
   
    labels:
      - "coolify.managed=true"
      - "coolify.port=5173"  

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=tienda
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: